name: Package
on:
  # Building on pull-requests, manual dispatch, and pushes to main. But restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: List installed modules
        run: pip list -v

      - name: Install prerequisites
        run: |
          # Ensure setuptools produces a PEP625-compliant sdist filename
          pip install 'setuptools>=69.3.0'

      - name: List installed modules again
        run: pip list -v
