name: macOS runners

on: workflow_dispatch

jobs:
  runner:
    runs-on: macos-${{ matrix.v }}
    strategy:
      matrix:
        v: ['11', '12', '13', '14', '15', 'latest']
    steps:
      - name: uname
        run:  uname -a
