name: Multiprocessing timing
on:
  workflow_dispatch:

permissions: {}

jobs:
  multi:
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [macos-15-intel, macos-26-intel, macos-15, macos-26, macos-latest, ubuntu-latest, ubuntu-26.04]

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - run: pip install pysam pytest

      - run: pytest -sv multi/testmulti.py
