name: Check outputs
on:
  workflow_dispatch:

jobs:
  testo:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        id: runtests
        run: |
          echo "rc=foobar" >> $GITHUB_OUTPUT

      - name: Build web front-end
        id: buildweb
        run: |
          echo "web_rc=bork" >> $GITHUB_OUTPUT

      - name: Fail if unit tests are not passing
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            core.setFailed('Unittests failed with rc = ${{ steps.runtests.outputs.rc }}')

      - name: Fail if unit tests are not passing
        continue-on-error: true
        env:
          rc: ${{ steps.runtests.outputs.rc }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Unittests failed with rc = ${rc}')

      - name: Fail if web build fails
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Web failed to build with rc = ${{ steps.runtests.outputs.web_rc }}')

      - name: Log them
        run: |
          echo steps.runtests.outputs.rc is ${{ steps.runtests.outputs.rc }}
          echo steps.runtests.outputs.web_rc is ${{ steps.runtests.outputs.web_rc }}
          echo steps.buildweb.outputs.rc is ${{ steps.buildweb.outputs.rc }}
          echo steps.buildweb.outputs.web_rc is ${{ steps.buildweb.outputs.web_rc }}
