name: Test interpolation
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_image:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'banana' && 'production' || 'dev' }}
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_DEV: australia-southeast1-docker.pkg.dev/cpg-common/images-dev/
      DOCKER_MAIN: australia-southeast1-docker.pkg.dev/cpg-common/images/

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - id: "google-cloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1051897107465/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gh-images-${{ github.ref_name == 'banana' && 'deployer' || 'dev-deployer' }}@cpg-common.iam.gserviceaccount.com"
